//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Top2000.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lijst
    {
        public int Songid { get; set; }
        public int Top2000jaar { get; set; }
        public int Positie { get; set; }
        public Nullable<int> Verschil { get; set; }
    
        public virtual Song Song { get; set; }
        public virtual Top2000Jaar Top2000Jaar1 { get; set; }
    }
}
